//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.18 at 02:22:38 PM BST 
//


package _int.iho.s100base;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CharacterSet19115_3.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CharacterSet19115_3"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ISO-10646-UCS-2"/&gt;
 *     &lt;enumeration value="ISO-10646-UCS-4"/&gt;
 *     &lt;enumeration value="ISO-10646-UCS-Basic"/&gt;
 *     &lt;enumeration value="ISO-10646-Unicode-Latin1"/&gt;
 *     &lt;enumeration value="ISO-10646-Unicode-J-1"/&gt;
 *     &lt;enumeration value="UTF-7"/&gt;
 *     &lt;enumeration value="UTF-8"/&gt;
 *     &lt;enumeration value="UTF-16"/&gt;
 *     &lt;enumeration value="UTF-16BE"/&gt;
 *     &lt;enumeration value="UTF-16LE"/&gt;
 *     &lt;enumeration value="ISO-8859-1"/&gt;
 *     &lt;enumeration value="ISO-8859-2"/&gt;
 *     &lt;enumeration value="ISO-8859-3"/&gt;
 *     &lt;enumeration value="ISO-8859-4"/&gt;
 *     &lt;enumeration value="ISO-8859-5"/&gt;
 *     &lt;enumeration value="ISO-8859-6"/&gt;
 *     &lt;enumeration value="ISO-8859-7"/&gt;
 *     &lt;enumeration value="ISO-8859-8"/&gt;
 *     &lt;enumeration value="ISO-8859-9"/&gt;
 *     &lt;enumeration value="ISO-8859-10"/&gt;
 *     &lt;enumeration value="ISO-8859-11"/&gt;
 *     &lt;enumeration value="ISO-8859-13"/&gt;
 *     &lt;enumeration value="ISO-8859-14"/&gt;
 *     &lt;enumeration value="ISO-8859-15"/&gt;
 *     &lt;enumeration value="ISO-8859-16"/&gt;
 *     &lt;enumeration value="JIS_Encoding"/&gt;
 *     &lt;enumeration value="Shift_JIS"/&gt;
 *     &lt;enumeration value="EUC-JP"/&gt;
 *     &lt;enumeration value="US-ASCII"/&gt;
 *     &lt;enumeration value="EUC-KR"/&gt;
 *     &lt;enumeration value="ISO-2022-KR"/&gt;
 *     &lt;enumeration value="Big5"/&gt;
 *     &lt;enumeration value="Big5-HKSCS"/&gt;
 *     &lt;enumeration value="ISO-10646-Unicode-Latin1"/&gt;
 *     &lt;enumeration value="ISO-10646-J-1"/&gt;
 *     &lt;enumeration value="PTCP154"/&gt;
 *     &lt;enumeration value="KOI8-U"/&gt;
 *     &lt;enumeration value="GB18030"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CharacterSet19115_3")
@XmlEnum
public enum CharacterSet191153 {

    @XmlEnumValue("ISO-10646-UCS-2")
    ISO_10646_UCS_2("ISO-10646-UCS-2"),
    @XmlEnumValue("ISO-10646-UCS-4")
    ISO_10646_UCS_4("ISO-10646-UCS-4"),
    @XmlEnumValue("ISO-10646-UCS-Basic")
    ISO_10646_UCS_BASIC("ISO-10646-UCS-Basic"),
    @XmlEnumValue("ISO-10646-Unicode-Latin1")
    ISO_10646_UNICODE_LATIN_1("ISO-10646-Unicode-Latin1"),
    @XmlEnumValue("ISO-10646-Unicode-J-1")
    ISO_10646_UNICODE_J_1("ISO-10646-Unicode-J-1"),
    @XmlEnumValue("UTF-7")
    UTF_7("UTF-7"),
    @XmlEnumValue("UTF-8")
    UTF_8("UTF-8"),
    @XmlEnumValue("UTF-16")
    UTF_16("UTF-16"),
    @XmlEnumValue("UTF-16BE")
    UTF_16_BE("UTF-16BE"),
    @XmlEnumValue("UTF-16LE")
    UTF_16_LE("UTF-16LE"),
    @XmlEnumValue("ISO-8859-1")
    ISO_8859_1("ISO-8859-1"),
    @XmlEnumValue("ISO-8859-2")
    ISO_8859_2("ISO-8859-2"),
    @XmlEnumValue("ISO-8859-3")
    ISO_8859_3("ISO-8859-3"),
    @XmlEnumValue("ISO-8859-4")
    ISO_8859_4("ISO-8859-4"),
    @XmlEnumValue("ISO-8859-5")
    ISO_8859_5("ISO-8859-5"),
    @XmlEnumValue("ISO-8859-6")
    ISO_8859_6("ISO-8859-6"),
    @XmlEnumValue("ISO-8859-7")
    ISO_8859_7("ISO-8859-7"),
    @XmlEnumValue("ISO-8859-8")
    ISO_8859_8("ISO-8859-8"),
    @XmlEnumValue("ISO-8859-9")
    ISO_8859_9("ISO-8859-9"),
    @XmlEnumValue("ISO-8859-10")
    ISO_8859_10("ISO-8859-10"),
    @XmlEnumValue("ISO-8859-11")
    ISO_8859_11("ISO-8859-11"),
    @XmlEnumValue("ISO-8859-13")
    ISO_8859_13("ISO-8859-13"),
    @XmlEnumValue("ISO-8859-14")
    ISO_8859_14("ISO-8859-14"),
    @XmlEnumValue("ISO-8859-15")
    ISO_8859_15("ISO-8859-15"),
    @XmlEnumValue("ISO-8859-16")
    ISO_8859_16("ISO-8859-16"),
    @XmlEnumValue("JIS_Encoding")
    JIS_ENCODING("JIS_Encoding"),
    @XmlEnumValue("Shift_JIS")
    SHIFT_JIS("Shift_JIS"),
    @XmlEnumValue("EUC-JP")
    EUC_JP("EUC-JP"),
    @XmlEnumValue("US-ASCII")
    US_ASCII("US-ASCII"),
    @XmlEnumValue("EUC-KR")
    EUC_KR("EUC-KR"),
    @XmlEnumValue("ISO-2022-KR")
    ISO_2022_KR("ISO-2022-KR"),
    @XmlEnumValue("Big5")
    BIG_5("Big5"),
    @XmlEnumValue("Big5-HKSCS")
    BIG_5_HKSCS("Big5-HKSCS"),
    @XmlEnumValue("ISO-10646-J-1")
    ISO_10646_J_1("ISO-10646-J-1"),
    @XmlEnumValue("PTCP154")
    PTCP_154("PTCP154"),
    @XmlEnumValue("KOI8-U")
    KOI_8_U("KOI8-U"),
    @XmlEnumValue("GB18030")
    GB_18030("GB18030");
    private final String value;

    CharacterSet191153(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CharacterSet191153 fromValue(String v) {
        for (CharacterSet191153 c: CharacterSet191153 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
