//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.20 at 12:23:53 PM BST 
//


package _int.iho.s100fd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the _int.iho.s100fd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: _int.iho.s100fd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Registry }
     * 
     */
    public Registry createRegistry() {
        return new Registry();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link S100RERegister }
     * 
     */
    public S100RERegister createS100RERegister() {
        return new S100RERegister();
    }

    /**
     * Create an instance of {@link ReferenceDocument }
     * 
     */
    public ReferenceDocument createReferenceDocument() {
        return new ReferenceDocument();
    }

    /**
     * Create an instance of {@link S100REReference }
     * 
     */
    public S100REReference createS100REReference() {
        return new S100REReference();
    }

    /**
     * Create an instance of {@link S100REReferenceSource }
     * 
     */
    public S100REReferenceSource createS100REReferenceSource() {
        return new S100REReferenceSource();
    }

    /**
     * Create an instance of {@link S100REManagementInfo }
     * 
     */
    public S100REManagementInfo createS100REManagementInfo() {
        return new S100REManagementInfo();
    }

    /**
     * Create an instance of {@link S100RERegisterItem }
     * 
     */
    public S100RERegisterItem createS100RERegisterItem() {
        return new S100RERegisterItem();
    }

    /**
     * Create an instance of {@link S100CDFeatureConcept }
     * 
     */
    public S100CDFeatureConcept createS100CDFeatureConcept() {
        return new S100CDFeatureConcept();
    }

    /**
     * Create an instance of {@link S100CDInformationConcept }
     * 
     */
    public S100CDInformationConcept createS100CDInformationConcept() {
        return new S100CDInformationConcept();
    }

    /**
     * Create an instance of {@link S100CDAttributeConstraints }
     * 
     */
    public S100CDAttributeConstraints createS100CDAttributeConstraints() {
        return new S100CDAttributeConstraints();
    }

    /**
     * Create an instance of {@link S100CDSimpleAttributeConcept }
     * 
     */
    public S100CDSimpleAttributeConcept createS100CDSimpleAttributeConcept() {
        return new S100CDSimpleAttributeConcept();
    }

    /**
     * Create an instance of {@link SubAttribute }
     * 
     */
    public SubAttribute createSubAttribute() {
        return new SubAttribute();
    }

    /**
     * Create an instance of {@link S100CDComplexAttributeConcept }
     * 
     */
    public S100CDComplexAttributeConcept createS100CDComplexAttributeConcept() {
        return new S100CDComplexAttributeConcept();
    }

    /**
     * Create an instance of {@link S100CDEnumeratedValueConcept }
     * 
     */
    public S100CDEnumeratedValueConcept createS100CDEnumeratedValueConcept() {
        return new S100CDEnumeratedValueConcept();
    }

    /**
     * Create an instance of {@link RegisterInformation }
     * 
     */
    public RegisterInformation createRegisterInformation() {
        return new RegisterInformation();
    }

    /**
     * Create an instance of {@link ReferenceDocuments }
     * 
     */
    public ReferenceDocuments createReferenceDocuments() {
        return new ReferenceDocuments();
    }

    /**
     * Create an instance of {@link S100CDFeatureConcepts }
     * 
     */
    public S100CDFeatureConcepts createS100CDFeatureConcepts() {
        return new S100CDFeatureConcepts();
    }

    /**
     * Create an instance of {@link S100CDInformationConcepts }
     * 
     */
    public S100CDInformationConcepts createS100CDInformationConcepts() {
        return new S100CDInformationConcepts();
    }

    /**
     * Create an instance of {@link S100CDSimpleAttributeConcepts }
     * 
     */
    public S100CDSimpleAttributeConcepts createS100CDSimpleAttributeConcepts() {
        return new S100CDSimpleAttributeConcepts();
    }

    /**
     * Create an instance of {@link S100CDComplexAttributeConcepts }
     * 
     */
    public S100CDComplexAttributeConcepts createS100CDComplexAttributeConcepts() {
        return new S100CDComplexAttributeConcepts();
    }

    /**
     * Create an instance of {@link S100CDEnumeratedValueConcepts }
     * 
     */
    public S100CDEnumeratedValueConcepts createS100CDEnumeratedValueConcepts() {
        return new S100CDEnumeratedValueConcepts();
    }

}
