//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.18 at 04:40:38 PM BST 
//


package _int.iho.s100fd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProposalType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProposalType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="addition"/&gt;
 *     &lt;enumeration value="clarification"/&gt;
 *     &lt;enumeration value="supersession"/&gt;
 *     &lt;enumeration value="retirement"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ProposalType")
@XmlEnum
public enum ProposalType {

    @XmlEnumValue("addition")
    ADDITION("addition"),
    @XmlEnumValue("clarification")
    CLARIFICATION("clarification"),
    @XmlEnumValue("supersession")
    SUPERSESSION("supersession"),
    @XmlEnumValue("retirement")
    RETIREMENT("retirement");
    private final String value;

    ProposalType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProposalType fromValue(String v) {
        for (ProposalType c: ProposalType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
