//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.18 at 04:40:38 PM BST 
//


package _int.iho.s100fd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for S100_CD_RegisterItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S100_CD_RegisterItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.iho.int/S100FD}S100_RE_RegisterItem"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="camelCaseId" type="{http://www.iho.int/S100FD}CamelCaseId"/&gt;
 *         &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="referenceSource" type="{http://www.iho.int/S100FD}S100_RE_ReferenceSource" minOccurs="0"/&gt;
 *         &lt;element name="S100_CD_reference" type="{http://www.iho.int/S100FD}S100_RE_Reference" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="managementInfo" type="{http://www.iho.int/S100FD}S100_RE_ManagementInfo" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S100_CD_RegisterItem", propOrder = {
    "camelCaseId",
    "alias",
    "referenceSource",
    "s100CDReference",
    "managementInfo"
})
@XmlSeeAlso({
    S100CDFeatureConcept.class,
    S100CDInformationConcept.class,
    S100CDAttributeConcept.class,
    S100CDEnumeratedValueConcept.class
})
public abstract class S100CDRegisterItem
    extends S100RERegisterItem
{

    @XmlElement(required = true)
    protected String camelCaseId;
    protected List<String> alias;
    protected S100REReferenceSource referenceSource;
    @XmlElement(name = "S100_CD_reference")
    protected List<S100REReference> s100CDReference;
    @XmlElement(required = true)
    protected List<S100REManagementInfo> managementInfo;

    /**
     * Gets the value of the camelCaseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCamelCaseId() {
        return camelCaseId;
    }

    /**
     * Sets the value of the camelCaseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCamelCaseId(String value) {
        this.camelCaseId = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlias().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAlias() {
        if (alias == null) {
            alias = new ArrayList<String>();
        }
        return this.alias;
    }

    /**
     * Gets the value of the referenceSource property.
     * 
     * @return
     *     possible object is
     *     {@link S100REReferenceSource }
     *     
     */
    public S100REReferenceSource getReferenceSource() {
        return referenceSource;
    }

    /**
     * Sets the value of the referenceSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100REReferenceSource }
     *     
     */
    public void setReferenceSource(S100REReferenceSource value) {
        this.referenceSource = value;
    }

    /**
     * Gets the value of the s100CDReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the s100CDReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getS100CDReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link S100REReference }
     * 
     * 
     */
    public List<S100REReference> getS100CDReference() {
        if (s100CDReference == null) {
            s100CDReference = new ArrayList<S100REReference>();
        }
        return this.s100CDReference;
    }

    /**
     * Gets the value of the managementInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the managementInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManagementInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link S100REManagementInfo }
     * 
     * 
     */
    public List<S100REManagementInfo> getManagementInfo() {
        if (managementInfo == null) {
            managementInfo = new ArrayList<S100REManagementInfo>();
        }
        return this.managementInfo;
    }

}
