//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.18 at 02:24:22 PM BST 
//


package _int.iho.s100fd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimilarityToSource.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SimilarityToSource"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="identical"/&gt;
 *     &lt;enumeration value="restyled"/&gt;
 *     &lt;enumeration value="contextAdded"/&gt;
 *     &lt;enumeration value="generalization"/&gt;
 *     &lt;enumeration value="specialization"/&gt;
 *     &lt;enumeration value="unspecified"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SimilarityToSource")
@XmlEnum
public enum SimilarityToSource {

    @XmlEnumValue("identical")
    IDENTICAL("identical"),
    @XmlEnumValue("restyled")
    RESTYLED("restyled"),
    @XmlEnumValue("contextAdded")
    CONTEXT_ADDED("contextAdded"),
    @XmlEnumValue("generalization")
    GENERALIZATION("generalization"),
    @XmlEnumValue("specialization")
    SPECIALIZATION("specialization"),
    @XmlEnumValue("unspecified")
    UNSPECIFIED("unspecified");
    private final String value;

    SimilarityToSource(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SimilarityToSource fromValue(String v) {
        for (SimilarityToSource c: SimilarityToSource.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
