//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.20 at 12:23:53 PM BST 
//


package org.iala_aism.g1128.v1_3.servicespecificationschema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import _int.iho.s100fc.S100FCFeatureCatalogue;


/**
 * 
 *                 If the service is S-100 compliant it shall link to an existing Feature Catalogue in the
 *                 featureCatalogue element. The other elements are then not used.
 *                 If the service is not S-100 compliant: The serviceDataModel is formally described in the
 *                 sub-element modelDefinition to achieve interoperability and decouple it from implementing physical
 *                 data models described in e.g. SOAP or REST. Encodings are formally described using sub-element
 *                 encoding. The model can either be described in-line, or existing schemata can be imported.
 *                 One service specification has one logical service model. Sub-element modelDefinition has to be
 *                 provided. Elements of a serviceDataModel are:
 *                 - featureCatalogue Reference to an S-100 compliant logical data model description. To be used to
 *                 be S-100 compliant, otherwise the modelDefinition attribute has to be used
 *                 - modelDefinition Only used if not S-100 compliant. The definition of the service data model
 *                 described
 *                 - encoding Only used if not S-100 compliant. The encoding of the attribute modelDefinition
 *             
 * 
 * <p>Java class for ServiceDataModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceDataModel"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="featureCatalogue" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element ref="{http://www.iho.int/S100FC}S100_FC_FeatureCatalogue"/&gt;
 *                 &lt;/all&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="modelDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="encoding" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceDataModel", propOrder = {

})
public class ServiceDataModel {

    protected ServiceDataModel.FeatureCatalogue featureCatalogue;
    protected String modelDefinition;
    protected String encoding;

    /**
     * Gets the value of the featureCatalogue property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceDataModel.FeatureCatalogue }
     *     
     */
    public ServiceDataModel.FeatureCatalogue getFeatureCatalogue() {
        return featureCatalogue;
    }

    /**
     * Sets the value of the featureCatalogue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceDataModel.FeatureCatalogue }
     *     
     */
    public void setFeatureCatalogue(ServiceDataModel.FeatureCatalogue value) {
        this.featureCatalogue = value;
    }

    /**
     * Gets the value of the modelDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelDefinition() {
        return modelDefinition;
    }

    /**
     * Sets the value of the modelDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelDefinition(String value) {
        this.modelDefinition = value;
    }

    /**
     * Gets the value of the encoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncoding() {
        return encoding;
    }

    /**
     * Sets the value of the encoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncoding(String value) {
        this.encoding = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element ref="{http://www.iho.int/S100FC}S100_FC_FeatureCatalogue"/&gt;
     *       &lt;/all&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class FeatureCatalogue {

        @XmlElement(name = "S100_FC_FeatureCatalogue", namespace = "http://www.iho.int/S100FC", required = true)
        protected S100FCFeatureCatalogue s100FCFeatureCatalogue;

        /**
         * Gets the value of the s100FCFeatureCatalogue property.
         * 
         * @return
         *     possible object is
         *     {@link S100FCFeatureCatalogue }
         *     
         */
        public S100FCFeatureCatalogue getS100FCFeatureCatalogue() {
            return s100FCFeatureCatalogue;
        }

        /**
         * Sets the value of the s100FCFeatureCatalogue property.
         * 
         * @param value
         *     allowed object is
         *     {@link S100FCFeatureCatalogue }
         *     
         */
        public void setS100FCFeatureCatalogue(S100FCFeatureCatalogue value) {
            this.s100FCFeatureCatalogue = value;
        }

    }

}
