//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 11:16:45 AM CEST 
//


package net.maritimeconnectivity.eNav.g1128.servicespecificationschema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.efficiensea2.maritime_cloud.service_registry.v1.servicespecificationschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.efficiensea2.maritime_cloud.service_registry.v1.servicespecificationschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceSpecification }
     *
     * @return ServiceSpecification instance
     */
    public ServiceSpecification createServiceSpecification() {
        return new ServiceSpecification();
    }

    /**
     * Create an instance of {@link Operation }
     *
     * @return Operation instance
     */
    public Operation createOperation() {
        return new Operation();
    }

    /**
     * Create an instance of {@link ConsumerInterface }
     *
     * @return ConsumerInterface instance
     */
    public ConsumerInterface createConsumerInterface() {
        return new ConsumerInterface();
    }

    /**
     * Create an instance of {@link ServiceInterface }
     *
     * @return ServiceInterface instance
     */
    public ServiceInterface createServiceInterface() {
        return new ServiceInterface();
    }

    /**
     * Create an instance of {@link Requirement }
     *
     * @return Requirement instance
     */
    public Requirement createRequirement() {
        return new Requirement();
    }

    /**
     * Create an instance of {@link ServiceSpecification.Requirements }
     *
     * @return ServiceSpecification.Requirements instance
     */
    public ServiceSpecification.Requirements createServiceSpecificationRequirements() {
        return new ServiceSpecification.Requirements();
    }

    /**
     * Create an instance of {@link ServiceSpecification.AuthorInfos }
     *
     * @return ServiceSpecification.AuthorInfos instance
     */
    public ServiceSpecification.AuthorInfos createServiceSpecificationAuthorInfos() {
        return new ServiceSpecification.AuthorInfos();
    }

    /**
     * Create an instance of {@link ServiceDataModel }
     *
     * @return ServiceDataModel instance
     */
    public ServiceDataModel createServiceDataModel() {
        return new ServiceDataModel();
    }

    /**
     * Create an instance of {@link ServiceSpecification.ServiceInterfaces }
     *
     * @return ServiceSpecification.ServiceInterfaces instance
     */
    public ServiceSpecification.ServiceInterfaces createServiceSpecificationServiceInterfaces() {
        return new ServiceSpecification.ServiceInterfaces();
    }

    /**
     * Create an instance of {@link AuthorInfo }
     *
     * @return AuthorInfo instance
     */
    public AuthorInfo createAuthorInfo() {
        return new AuthorInfo();
    }

    /**
     * Create an instance of {@link VendorInfo }
     *
     * @return VendorInfo instance
     */
    public VendorInfo createVendorInfo() {
        return new VendorInfo();
    }

    /**
     * Create an instance of {@link ValueTypeDataModelMapping }
     *
     * @return ValueTypeDataModelMapping instance
     */
    public ValueTypeDataModelMapping createValueTypeDataModelMapping() {
        return new ValueTypeDataModelMapping();
    }

    /**
     * Create an instance of {@link Operation.ParameterTypes }
     *
     * @return Operation.ParameterTypes instance
     */
    public Operation.ParameterTypes createOperationParameterTypes() {
        return new Operation.ParameterTypes();
    }

    /**
     * Create an instance of {@link ConsumerInterface.Operations }
     *
     * @return ConsumerInterface.Operations instance
     */
    public ConsumerInterface.Operations createConsumerInterfaceOperations() {
        return new ConsumerInterface.Operations();
    }

    /**
     * Create an instance of {@link ServiceInterface.Operations }
     *
     * @return ServiceInterface.Operations instance
     */
    public ServiceInterface.Operations createServiceInterfaceOperations() {
        return new ServiceInterface.Operations();
    }

    /**
     * Create an instance of {@link Requirement.AuthorInfos }
     *
     * @return Requirement.AuthorInfos instance
     */
    public Requirement.AuthorInfos createRequirementAuthorInfos() {
        return new Requirement.AuthorInfos();
    }

}
