//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.10 at 12:40:55 PM BST 
//


package org.efficiensea2.maritime_cloud.service_registry.v1.serviceinstanceschema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.efficiensea2.maritime_cloud.service_registry.v1.serviceinstanceschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.efficiensea2.maritime_cloud.service_registry.v1.serviceinstanceschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceInstance }
     * 
     */
    public ServiceInstance createServiceInstance() {
        return new ServiceInstance();
    }

    /**
     * Create an instance of {@link ServiceLevel }
     * 
     */
    public ServiceLevel createServiceLevel() {
        return new ServiceLevel();
    }

    /**
     * Create an instance of {@link CoverageInfo }
     * 
     */
    public CoverageInfo createCoverageInfo() {
        return new CoverageInfo();
    }

    /**
     * Create an instance of {@link ServiceDesignReference }
     * 
     */
    public ServiceDesignReference createServiceDesignReference() {
        return new ServiceDesignReference();
    }

    /**
     * Create an instance of {@link CoverageArea }
     * 
     */
    public CoverageArea createCoverageArea() {
        return new CoverageArea();
    }

}
