//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.10 at 12:40:55 PM BST 
//


package _int.iho.s100fc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the _int.iho.s100fc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: _int.iho.s100fc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link S100FCFeatureCatalogue }
     * 
     */
    public S100FCFeatureCatalogue createS100FCFeatureCatalogue() {
        return new S100FCFeatureCatalogue();
    }

    /**
     * Create an instance of {@link S100FCDefinitionSources }
     * 
     */
    public S100FCDefinitionSources createS100FCDefinitionSources() {
        return new S100FCDefinitionSources();
    }

    /**
     * Create an instance of {@link S100FCSimpleAttributes }
     * 
     */
    public S100FCSimpleAttributes createS100FCSimpleAttributes() {
        return new S100FCSimpleAttributes();
    }

    /**
     * Create an instance of {@link S100FCComplexAttributes }
     * 
     */
    public S100FCComplexAttributes createS100FCComplexAttributes() {
        return new S100FCComplexAttributes();
    }

    /**
     * Create an instance of {@link S100FCRoles }
     * 
     */
    public S100FCRoles createS100FCRoles() {
        return new S100FCRoles();
    }

    /**
     * Create an instance of {@link S100FCInformationAssociations }
     * 
     */
    public S100FCInformationAssociations createS100FCInformationAssociations() {
        return new S100FCInformationAssociations();
    }

    /**
     * Create an instance of {@link S100FCFeatureAssociations }
     * 
     */
    public S100FCFeatureAssociations createS100FCFeatureAssociations() {
        return new S100FCFeatureAssociations();
    }

    /**
     * Create an instance of {@link S100FCInformationTypes }
     * 
     */
    public S100FCInformationTypes createS100FCInformationTypes() {
        return new S100FCInformationTypes();
    }

    /**
     * Create an instance of {@link S100FCFeatureTypes }
     * 
     */
    public S100FCFeatureTypes createS100FCFeatureTypes() {
        return new S100FCFeatureTypes();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link FCDefinitionSource }
     * 
     */
    public FCDefinitionSource createFCDefinitionSource() {
        return new FCDefinitionSource();
    }

    /**
     * Create an instance of {@link FCDefinitionReference }
     * 
     */
    public FCDefinitionReference createFCDefinitionReference() {
        return new FCDefinitionReference();
    }

    /**
     * Create an instance of {@link ValueList }
     * 
     */
    public ValueList createValueList() {
        return new ValueList();
    }

    /**
     * Create an instance of {@link S100FCListedValues }
     * 
     */
    public S100FCListedValues createS100FCListedValues() {
        return new S100FCListedValues();
    }

    /**
     * Create an instance of {@link S100FCAttributeBinding }
     * 
     */
    public S100FCAttributeBinding createS100FCAttributeBinding() {
        return new S100FCAttributeBinding();
    }

    /**
     * Create an instance of {@link S100FCInformationBinding }
     * 
     */
    public S100FCInformationBinding createS100FCInformationBinding() {
        return new S100FCInformationBinding();
    }

    /**
     * Create an instance of {@link S100FCFeatureBinding }
     * 
     */
    public S100FCFeatureBinding createS100FCFeatureBinding() {
        return new S100FCFeatureBinding();
    }

    /**
     * Create an instance of {@link S100FCListedValue }
     * 
     */
    public S100FCListedValue createS100FCListedValue() {
        return new S100FCListedValue();
    }

    /**
     * Create an instance of {@link S100FCAttribute }
     * 
     */
    public S100FCAttribute createS100FCAttribute() {
        return new S100FCAttribute();
    }

    /**
     * Create an instance of {@link S100FCSimpleAttribute }
     * 
     */
    public S100FCSimpleAttribute createS100FCSimpleAttribute() {
        return new S100FCSimpleAttribute();
    }

    /**
     * Create an instance of {@link S100FCComplexAttribute }
     * 
     */
    public S100FCComplexAttribute createS100FCComplexAttribute() {
        return new S100FCComplexAttribute();
    }

    /**
     * Create an instance of {@link S100FCRole }
     * 
     */
    public S100FCRole createS100FCRole() {
        return new S100FCRole();
    }

    /**
     * Create an instance of {@link S100FCInformationAssociation }
     * 
     */
    public S100FCInformationAssociation createS100FCInformationAssociation() {
        return new S100FCInformationAssociation();
    }

    /**
     * Create an instance of {@link S100FCFeatureAssociation }
     * 
     */
    public S100FCFeatureAssociation createS100FCFeatureAssociation() {
        return new S100FCFeatureAssociation();
    }

    /**
     * Create an instance of {@link S100FCInformationType }
     * 
     */
    public S100FCInformationType createS100FCInformationType() {
        return new S100FCInformationType();
    }

    /**
     * Create an instance of {@link S100FCFeatureType }
     * 
     */
    public S100FCFeatureType createS100FCFeatureType() {
        return new S100FCFeatureType();
    }

}
