//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.18 at 02:04:50 PM BST 
//


package _int.iho.s100fc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import _int.iho.s100ci.CIResponsibility;
import _int.iho.s100ci.MDClassificationCode;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="scope" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fieldOfApplication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="versionNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="versionDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="producer" type="{http://www.iho.int/S100CI}CI_Responsibility_Type"/&gt;
 *         &lt;element name="classification" type="{http://www.iho.int/S100CI}MD_ClassificationCode" minOccurs="0"/&gt;
 *         &lt;element name="S100_FC_DefinitionSources" type="{http://www.iho.int/S100FC}S100_FC_DefinitionSources" minOccurs="0"/&gt;
 *         &lt;element name="S100_FC_SimpleAttributes" type="{http://www.iho.int/S100FC}S100_FC_SimpleAttributes" minOccurs="0"/&gt;
 *         &lt;element name="S100_FC_ComplexAttributes" type="{http://www.iho.int/S100FC}S100_FC_ComplexAttributes" minOccurs="0"/&gt;
 *         &lt;element name="S100_FC_Roles" type="{http://www.iho.int/S100FC}S100_FC_Roles" minOccurs="0"/&gt;
 *         &lt;element name="S100_FC_InformationAssociations" type="{http://www.iho.int/S100FC}S100_FC_InformationAssociations" minOccurs="0"/&gt;
 *         &lt;element name="S100_FC_FeatureAssociations" type="{http://www.iho.int/S100FC}S100_FC_FeatureAssociations" minOccurs="0"/&gt;
 *         &lt;element name="S100_FC_InformationTypes" type="{http://www.iho.int/S100FC}S100_FC_InformationTypes" minOccurs="0"/&gt;
 *         &lt;element name="S100_FC_FeatureTypes" type="{http://www.iho.int/S100FC}S100_FC_FeatureTypes" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "scope",
    "fieldOfApplication",
    "versionNumber",
    "versionDate",
    "producer",
    "classification",
    "s100FCDefinitionSources",
    "s100FCSimpleAttributes",
    "s100FCComplexAttributes",
    "s100FCRoles",
    "s100FCInformationAssociations",
    "s100FCFeatureAssociations",
    "s100FCInformationTypes",
    "s100FCFeatureTypes"
})
@XmlRootElement(name = "S100_FC_FeatureCatalogue")
public class S100FCFeatureCatalogue {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String scope;
    protected String fieldOfApplication;
    @XmlElement(required = true)
    protected String versionNumber;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar versionDate;
    @XmlElement(required = true)
    protected CIResponsibility producer;
    @XmlSchemaType(name = "string")
    protected MDClassificationCode classification;
    @XmlElement(name = "S100_FC_DefinitionSources")
    protected S100FCDefinitionSources s100FCDefinitionSources;
    @XmlElement(name = "S100_FC_SimpleAttributes")
    protected S100FCSimpleAttributes s100FCSimpleAttributes;
    @XmlElement(name = "S100_FC_ComplexAttributes")
    protected S100FCComplexAttributes s100FCComplexAttributes;
    @XmlElement(name = "S100_FC_Roles")
    protected S100FCRoles s100FCRoles;
    @XmlElement(name = "S100_FC_InformationAssociations")
    protected S100FCInformationAssociations s100FCInformationAssociations;
    @XmlElement(name = "S100_FC_FeatureAssociations")
    protected S100FCFeatureAssociations s100FCFeatureAssociations;
    @XmlElement(name = "S100_FC_InformationTypes")
    protected S100FCInformationTypes s100FCInformationTypes;
    @XmlElement(name = "S100_FC_FeatureTypes")
    protected S100FCFeatureTypes s100FCFeatureTypes;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScope(String value) {
        this.scope = value;
    }

    /**
     * Gets the value of the fieldOfApplication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldOfApplication() {
        return fieldOfApplication;
    }

    /**
     * Sets the value of the fieldOfApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldOfApplication(String value) {
        this.fieldOfApplication = value;
    }

    /**
     * Gets the value of the versionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionNumber() {
        return versionNumber;
    }

    /**
     * Sets the value of the versionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionNumber(String value) {
        this.versionNumber = value;
    }

    /**
     * Gets the value of the versionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVersionDate() {
        return versionDate;
    }

    /**
     * Sets the value of the versionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVersionDate(XMLGregorianCalendar value) {
        this.versionDate = value;
    }

    /**
     * Gets the value of the producer property.
     * 
     * @return
     *     possible object is
     *     {@link CIResponsibility }
     *     
     */
    public CIResponsibility getProducer() {
        return producer;
    }

    /**
     * Sets the value of the producer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIResponsibility }
     *     
     */
    public void setProducer(CIResponsibility value) {
        this.producer = value;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link MDClassificationCode }
     *     
     */
    public MDClassificationCode getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDClassificationCode }
     *     
     */
    public void setClassification(MDClassificationCode value) {
        this.classification = value;
    }

    /**
     * Gets the value of the s100FCDefinitionSources property.
     * 
     * @return
     *     possible object is
     *     {@link S100FCDefinitionSources }
     *     
     */
    public S100FCDefinitionSources getS100FCDefinitionSources() {
        return s100FCDefinitionSources;
    }

    /**
     * Sets the value of the s100FCDefinitionSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100FCDefinitionSources }
     *     
     */
    public void setS100FCDefinitionSources(S100FCDefinitionSources value) {
        this.s100FCDefinitionSources = value;
    }

    /**
     * Gets the value of the s100FCSimpleAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link S100FCSimpleAttributes }
     *     
     */
    public S100FCSimpleAttributes getS100FCSimpleAttributes() {
        return s100FCSimpleAttributes;
    }

    /**
     * Sets the value of the s100FCSimpleAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100FCSimpleAttributes }
     *     
     */
    public void setS100FCSimpleAttributes(S100FCSimpleAttributes value) {
        this.s100FCSimpleAttributes = value;
    }

    /**
     * Gets the value of the s100FCComplexAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link S100FCComplexAttributes }
     *     
     */
    public S100FCComplexAttributes getS100FCComplexAttributes() {
        return s100FCComplexAttributes;
    }

    /**
     * Sets the value of the s100FCComplexAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100FCComplexAttributes }
     *     
     */
    public void setS100FCComplexAttributes(S100FCComplexAttributes value) {
        this.s100FCComplexAttributes = value;
    }

    /**
     * Gets the value of the s100FCRoles property.
     * 
     * @return
     *     possible object is
     *     {@link S100FCRoles }
     *     
     */
    public S100FCRoles getS100FCRoles() {
        return s100FCRoles;
    }

    /**
     * Sets the value of the s100FCRoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100FCRoles }
     *     
     */
    public void setS100FCRoles(S100FCRoles value) {
        this.s100FCRoles = value;
    }

    /**
     * Gets the value of the s100FCInformationAssociations property.
     * 
     * @return
     *     possible object is
     *     {@link S100FCInformationAssociations }
     *     
     */
    public S100FCInformationAssociations getS100FCInformationAssociations() {
        return s100FCInformationAssociations;
    }

    /**
     * Sets the value of the s100FCInformationAssociations property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100FCInformationAssociations }
     *     
     */
    public void setS100FCInformationAssociations(S100FCInformationAssociations value) {
        this.s100FCInformationAssociations = value;
    }

    /**
     * Gets the value of the s100FCFeatureAssociations property.
     * 
     * @return
     *     possible object is
     *     {@link S100FCFeatureAssociations }
     *     
     */
    public S100FCFeatureAssociations getS100FCFeatureAssociations() {
        return s100FCFeatureAssociations;
    }

    /**
     * Sets the value of the s100FCFeatureAssociations property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100FCFeatureAssociations }
     *     
     */
    public void setS100FCFeatureAssociations(S100FCFeatureAssociations value) {
        this.s100FCFeatureAssociations = value;
    }

    /**
     * Gets the value of the s100FCInformationTypes property.
     * 
     * @return
     *     possible object is
     *     {@link S100FCInformationTypes }
     *     
     */
    public S100FCInformationTypes getS100FCInformationTypes() {
        return s100FCInformationTypes;
    }

    /**
     * Sets the value of the s100FCInformationTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100FCInformationTypes }
     *     
     */
    public void setS100FCInformationTypes(S100FCInformationTypes value) {
        this.s100FCInformationTypes = value;
    }

    /**
     * Gets the value of the s100FCFeatureTypes property.
     * 
     * @return
     *     possible object is
     *     {@link S100FCFeatureTypes }
     *     
     */
    public S100FCFeatureTypes getS100FCFeatureTypes() {
        return s100FCFeatureTypes;
    }

    /**
     * Sets the value of the s100FCFeatureTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100FCFeatureTypes }
     *     
     */
    public void setS100FCFeatureTypes(S100FCFeatureTypes value) {
        this.s100FCFeatureTypes = value;
    }

}
