//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 11:16:45 AM CEST 
//


package _int.iho.s100fc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for S100_FC_ComplexAttribute complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S100_FC_ComplexAttribute"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.iho.int/S100FC}S100_FC_Attribute"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="subAttributeBinding" type="{http://www.iho.int/S100FC}S100_FC_AttributeBinding" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S100_FC_ComplexAttribute", propOrder = {
    "subAttributeBindings"
})
public class S100FCComplexAttribute
    extends S100FCAttribute
{

    @XmlElement(name = "subAttributeBinding", required = true)
    protected List<S100FCAttributeBinding> subAttributeBindings;

    /**
     * Gets the value of the subAttributeBindings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subAttributeBindings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubAttributeBindings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link S100FCAttributeBinding }
     * 
     * @return list of S100FCAttributeBinding
     */
    public List<S100FCAttributeBinding> getSubAttributeBindings() {
        if (subAttributeBindings == null) {
            subAttributeBindings = new ArrayList<S100FCAttributeBinding>();
        }
        return this.subAttributeBindings;
    }

}
