//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.21 at 10:03:52 AM BST 
//


package _int.iho.s100fc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import _int.iho.s100base.S100Multiplicity;


/**
 * <p>Java class for S100_FC_AttributeBinding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S100_FC_AttributeBinding"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="multiplicity" type="{http://www.iho.int/S100Base}S100_Multiplicity"/&gt;
 *         &lt;element name="permittedValues" type="{http://www.iho.int/S100FC}ValueList" minOccurs="0"/&gt;
 *         &lt;element name="attribute" type="{http://www.iho.int/S100FC}Reference"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="sequential" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S100_FC_AttributeBinding", propOrder = {
    "multiplicity",
    "permittedValues",
    "attribute"
})
public class S100FCAttributeBinding {

    @XmlElement(required = true)
    protected S100Multiplicity multiplicity;
    protected ValueList permittedValues;
    @XmlElement(required = true)
    protected Reference attribute;
    @XmlAttribute(name = "sequential")
    protected Boolean sequential;

    /**
     * Gets the value of the multiplicity property.
     * 
     * @return
     *     possible object is
     *     {@link S100Multiplicity }
     *     
     */
    public S100Multiplicity getMultiplicity() {
        return multiplicity;
    }

    /**
     * Sets the value of the multiplicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100Multiplicity }
     *     
     */
    public void setMultiplicity(S100Multiplicity value) {
        this.multiplicity = value;
    }

    /**
     * Gets the value of the permittedValues property.
     * 
     * @return
     *     possible object is
     *     {@link ValueList }
     *     
     */
    public ValueList getPermittedValues() {
        return permittedValues;
    }

    /**
     * Sets the value of the permittedValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueList }
     *     
     */
    public void setPermittedValues(ValueList value) {
        this.permittedValues = value;
    }

    /**
     * Gets the value of the attribute property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getAttribute() {
        return attribute;
    }

    /**
     * Sets the value of the attribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setAttribute(Reference value) {
        this.attribute = value;
    }

    /**
     * Gets the value of the sequential property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSequential() {
        if (sequential == null) {
            return false;
        } else {
            return sequential;
        }
    }

    /**
     * Sets the value of the sequential property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSequential(Boolean value) {
        this.sequential = value;
    }

}
