//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.18 at 02:04:50 PM BST 
//


package _int.iho.s100fc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import _int.iho.s100base.S100Multiplicity;


/**
 * <p>Java class for S100_FC_InformationBinding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S100_FC_InformationBinding"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="multiplicity" type="{http://www.iho.int/S100Base}S100_Multiplicity"/&gt;
 *         &lt;element name="association" type="{http://www.iho.int/S100FC}Reference"/&gt;
 *         &lt;element name="role" type="{http://www.iho.int/S100FC}Reference" minOccurs="0"/&gt;
 *         &lt;element name="informationType" type="{http://www.iho.int/S100FC}Reference"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="roleType" use="required" type="{http://www.iho.int/S100FC}S100_FC_RoleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S100_FC_InformationBinding", propOrder = {
    "multiplicity",
    "association",
    "role",
    "informationType"
})
public class S100FCInformationBinding {

    @XmlElement(required = true)
    protected S100Multiplicity multiplicity;
    @XmlElement(required = true)
    protected Reference association;
    protected Reference role;
    @XmlElement(required = true)
    protected Reference informationType;
    @XmlAttribute(name = "roleType", required = true)
    protected S100FCRoleType roleType;

    /**
     * Gets the value of the multiplicity property.
     * 
     * @return
     *     possible object is
     *     {@link S100Multiplicity }
     *     
     */
    public S100Multiplicity getMultiplicity() {
        return multiplicity;
    }

    /**
     * Sets the value of the multiplicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100Multiplicity }
     *     
     */
    public void setMultiplicity(S100Multiplicity value) {
        this.multiplicity = value;
    }

    /**
     * Gets the value of the association property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getAssociation() {
        return association;
    }

    /**
     * Sets the value of the association property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setAssociation(Reference value) {
        this.association = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setRole(Reference value) {
        this.role = value;
    }

    /**
     * Gets the value of the informationType property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getInformationType() {
        return informationType;
    }

    /**
     * Sets the value of the informationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setInformationType(Reference value) {
        this.informationType = value;
    }

    /**
     * Gets the value of the roleType property.
     * 
     * @return
     *     possible object is
     *     {@link S100FCRoleType }
     *     
     */
    public S100FCRoleType getRoleType() {
        return roleType;
    }

    /**
     * Sets the value of the roleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100FCRoleType }
     *     
     */
    public void setRoleType(S100FCRoleType value) {
        this.roleType = value;
    }

}
