//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.14 at 11:16:45 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://efficiensea2.org/maritime-cloud/service-registry/v1/ServiceDesignSchema.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.maritimeconnectivity.eNav.g1128.servicedesignschema;
