//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.18 at 09:15:36 AM BST 
//


package org.efficiensea2.maritime_cloud.service_registry.v1.servicedesignschema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.efficiensea2.maritime_cloud.service_registry.v1.servicedesignschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ServiceDesign_QNAME = new QName("http://efficiensea2.org/maritime-cloud/service-registry/v1/ServiceDesignSchema.xsd", "serviceDesign");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.efficiensea2.maritime_cloud.service_registry.v1.servicedesignschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceDesign }
     * 
     */
    public ServiceDesign createServiceDesign() {
        return new ServiceDesign();
    }

    /**
     * Create an instance of {@link ServiceSpecificationReference }
     * 
     */
    public ServiceSpecificationReference createServiceSpecificationReference() {
        return new ServiceSpecificationReference();
    }

    /**
     * Create an instance of {@link Transport }
     * 
     */
    public Transport createTransport() {
        return new Transport();
    }

    /**
     * Create an instance of {@link ServicePhysicalDataModel }
     * 
     */
    public ServicePhysicalDataModel createServicePhysicalDataModel() {
        return new ServicePhysicalDataModel();
    }

    /**
     * Create an instance of {@link ServiceDesign.OffersTransport }
     * 
     */
    public ServiceDesign.OffersTransport createServiceDesignOffersTransport() {
        return new ServiceDesign.OffersTransport();
    }

    /**
     * Create an instance of {@link ServiceDesign.DesignsServiceSpecifications }
     * 
     */
    public ServiceDesign.DesignsServiceSpecifications createServiceDesignDesignsServiceSpecifications() {
        return new ServiceDesign.DesignsServiceSpecifications();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceDesign }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ServiceDesign }{@code >}
     */
    @XmlElementDecl(namespace = "http://efficiensea2.org/maritime-cloud/service-registry/v1/ServiceDesignSchema.xsd", name = "serviceDesign")
    public JAXBElement<ServiceDesign> createServiceDesign(ServiceDesign value) {
        return new JAXBElement<ServiceDesign>(_ServiceDesign_QNAME, ServiceDesign.class, null, value);
    }

}
