//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.10 at 12:40:55 PM BST 
//


package org.efficiensea2.maritime_cloud.service_registry.v1.servicedesignschema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.efficiensea2.maritime_cloud.service_registry.v1.servicespecificationschema.ServiceStatus;
import org.efficiensea2.maritime_cloud.service_registry.v1.servicespecificationschema.VendorInfo;


/**
 * 
 *                 A service technical design description.
 * 
 *                 Elements of a serviceDesign are:
 * 
 *                 - name The human readable name of the service design The name shall be at maximum a one-line brief
 *                   label. Newer versions of the same service design shall adopt the same name.
 * 
 *                 - id Globally unique identification of the service design Newer versions of the same service
 *                   design shall adopt the same id.
 * 
 *                 - version Version of the service design. A service design is uniquely identified by its id and
 *                   version. Any change in the service physical data model or in the service specification reference
 *                   requires a new version of the service design.
 * 
 *                 - status Status of the service design. One of the values 'provisional', 'released',
 *                   'deprecated', 'deleted'.
 * 
 *                 - description A human readable short description of the service design. The description shall
 *                   contain an abstract of what a service implementation actually does.
 * 
 *                 - designsServiceSpecifications
 *                   Refers to service specification(s) that is/are realized by this service design. As a minimum,
 *                   one service specification shall be referenced. One service design may realise several service
 *                   specification (either different versions of one specification, or even different
 *                   specifications).
 * 
 *                 - offersTransport Refers to transport technologies offered by the service design. At
 *                   least one reference shall be provided.
 * 
 *                 - designedBy Mandatory reference to information about the author of the service design.
 * 
 *                 - servicePhysicalDataModel
 *                   Mandatory reference to the service physical data model description.
 *             
 * 
 * <p>Java class for ServiceDesign complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceDesign"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="id" type="{http://efficiensea2.org/maritime-cloud/service-registry/v1/ServiceSpecificationSchema.xsd}ServiceIdentifier"/&gt;
 *         &lt;element name="version" type="{http://efficiensea2.org/maritime-cloud/service-registry/v1/ServiceSpecificationSchema.xsd}ServiceVersion"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="status" type="{http://efficiensea2.org/maritime-cloud/service-registry/v1/ServiceSpecificationSchema.xsd}ServiceStatus"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="offersTransport"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="offersTransport" type="{http://efficiensea2.org/maritime-cloud/service-registry/v1/ServiceDesignSchema.xsd}Transport" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="designsServiceSpecifications"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="designsServiceSpecifications" type="{http://efficiensea2.org/maritime-cloud/service-registry/v1/ServiceDesignSchema.xsd}ServiceSpecificationReference" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="designedBy" type="{http://efficiensea2.org/maritime-cloud/service-registry/v1/ServiceSpecificationSchema.xsd}VendorInfo"/&gt;
 *         &lt;element name="servicePhysicalDataModel" type="{http://efficiensea2.org/maritime-cloud/service-registry/v1/ServiceDesignSchema.xsd}ServicePhysicalDataModel"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceDesign", propOrder = {

})
@XmlRootElement(name = "serviceDesign")
public class ServiceDesign {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String version;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ServiceStatus status;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected ServiceDesign.OffersTransport offersTransport;
    @XmlElement(required = true)
    protected ServiceDesign.DesignsServiceSpecifications designsServiceSpecifications;
    @XmlElement(required = true)
    protected VendorInfo designedBy;
    @XmlElement(required = true)
    protected ServicePhysicalDataModel servicePhysicalDataModel;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceStatus }
     *     
     */
    public ServiceStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceStatus }
     *     
     */
    public void setStatus(ServiceStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the offersTransport property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceDesign.OffersTransport }
     *     
     */
    public ServiceDesign.OffersTransport getOffersTransport() {
        return offersTransport;
    }

    /**
     * Sets the value of the offersTransport property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceDesign.OffersTransport }
     *     
     */
    public void setOffersTransport(ServiceDesign.OffersTransport value) {
        this.offersTransport = value;
    }

    /**
     * Gets the value of the designsServiceSpecifications property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceDesign.DesignsServiceSpecifications }
     *     
     */
    public ServiceDesign.DesignsServiceSpecifications getDesignsServiceSpecifications() {
        return designsServiceSpecifications;
    }

    /**
     * Sets the value of the designsServiceSpecifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceDesign.DesignsServiceSpecifications }
     *     
     */
    public void setDesignsServiceSpecifications(ServiceDesign.DesignsServiceSpecifications value) {
        this.designsServiceSpecifications = value;
    }

    /**
     * Gets the value of the designedBy property.
     * 
     * @return
     *     possible object is
     *     {@link VendorInfo }
     *     
     */
    public VendorInfo getDesignedBy() {
        return designedBy;
    }

    /**
     * Sets the value of the designedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorInfo }
     *     
     */
    public void setDesignedBy(VendorInfo value) {
        this.designedBy = value;
    }

    /**
     * Gets the value of the servicePhysicalDataModel property.
     * 
     * @return
     *     possible object is
     *     {@link ServicePhysicalDataModel }
     *     
     */
    public ServicePhysicalDataModel getServicePhysicalDataModel() {
        return servicePhysicalDataModel;
    }

    /**
     * Sets the value of the servicePhysicalDataModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicePhysicalDataModel }
     *     
     */
    public void setServicePhysicalDataModel(ServicePhysicalDataModel value) {
        this.servicePhysicalDataModel = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="designsServiceSpecifications" type="{http://efficiensea2.org/maritime-cloud/service-registry/v1/ServiceDesignSchema.xsd}ServiceSpecificationReference" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "designsServiceSpecifications"
    })
    public static class DesignsServiceSpecifications {

        @XmlElement(required = true)
        protected List<ServiceSpecificationReference> designsServiceSpecifications;

        /**
         * Gets the value of the designsServiceSpecifications property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the designsServiceSpecifications property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDesignsServiceSpecifications().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ServiceSpecificationReference }
         * 
         * 
         */
        public List<ServiceSpecificationReference> getDesignsServiceSpecifications() {
            if (designsServiceSpecifications == null) {
                designsServiceSpecifications = new ArrayList<ServiceSpecificationReference>();
            }
            return this.designsServiceSpecifications;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="offersTransport" type="{http://efficiensea2.org/maritime-cloud/service-registry/v1/ServiceDesignSchema.xsd}Transport" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "offersTransports"
    })
    public static class OffersTransport {

        @XmlElement(name = "offersTransport", required = true)
        protected List<Transport> offersTransports;

        /**
         * Gets the value of the offersTransports property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the offersTransports property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOffersTransports().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Transport }
         * 
         * 
         */
        public List<Transport> getOffersTransports() {
            if (offersTransports == null) {
                offersTransports = new ArrayList<Transport>();
            }
            return this.offersTransports;
        }

    }

}
