//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.18 at 02:22:38 PM BST 
//


package _int.iho.s100ci;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * S-100 V. 4.0.0: use of references and nilling not allowed when used in S-100 feature catalogues
 * 
 * <p>Java class for CI_Responsibility_PropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CI_Responsibility_PropertyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element ref="{http://www.iho.int/S100CI}CI_Responsibility"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CI_Responsibility_PropertyType", propOrder = {
    "ciResponsibility"
})
public class CIResponsibilityPropertyType {

    @XmlElement(name = "CI_Responsibility")
    protected CIResponsibility ciResponsibility;

    /**
     * Gets the value of the ciResponsibility property.
     * 
     * @return
     *     possible object is
     *     {@link CIResponsibility }
     *     
     */
    public CIResponsibility getCIResponsibility() {
        return ciResponsibility;
    }

    /**
     * Sets the value of the ciResponsibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIResponsibility }
     *     
     */
    public void setCIResponsibility(CIResponsibility value) {
        this.ciResponsibility = value;
    }

}
