//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.10 at 02:50:37 PM GMT 
//


package _int.iho.s100ci;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DateTypeCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DateTypeCode"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="creation"/&gt;
 *     &lt;enumeration value="publication"/&gt;
 *     &lt;enumeration value="revision"/&gt;
 *     &lt;enumeration value="expiry"/&gt;
 *     &lt;enumeration value="lastUpdate"/&gt;
 *     &lt;enumeration value="lastRevision"/&gt;
 *     &lt;enumeration value="nextUpdate"/&gt;
 *     &lt;enumeration value="unavailable"/&gt;
 *     &lt;enumeration value="inForce"/&gt;
 *     &lt;enumeration value="adopted"/&gt;
 *     &lt;enumeration value="deprecated"/&gt;
 *     &lt;enumeration value="superseded"/&gt;
 *     &lt;enumeration value="validityBegins"/&gt;
 *     &lt;enumeration value="validityExpires"/&gt;
 *     &lt;enumeration value="released"/&gt;
 *     &lt;enumeration value="distribution"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DateTypeCode")
@XmlEnum
public enum DateTypeCode {


    /**
     * date identifies when the resource was brought into existence
     * 
     */
    @XmlEnumValue("creation")
    CREATION("creation"),

    /**
     * date identifies when the resource was issued
     * 
     */
    @XmlEnumValue("publication")
    PUBLICATION("publication"),

    /**
     * date identifies when the resource was examined or re-examined and improved or amended
     * 
     */
    @XmlEnumValue("revision")
    REVISION("revision"),

    /**
     * date identifies when resource expires
     * 
     */
    @XmlEnumValue("expiry")
    EXPIRY("expiry"),

    /**
     * date identifies when resource was last updated
     * 
     */
    @XmlEnumValue("lastUpdate")
    LAST_UPDATE("lastUpdate"),

    /**
     * date identifies when resource was last reviewed
     * 
     */
    @XmlEnumValue("lastRevision")
    LAST_REVISION("lastRevision"),

    /**
     * date identifies when resource will be next updated
     * 
     */
    @XmlEnumValue("nextUpdate")
    NEXT_UPDATE("nextUpdate"),

    /**
     * date identifies when resource became not available or obtainable
     * 
     */
    @XmlEnumValue("unavailable")
    UNAVAILABLE("unavailable"),

    /**
     * date identifies when resource became in force
     * 
     */
    @XmlEnumValue("inForce")
    IN_FORCE("inForce"),

    /**
     * date identifies when resource was adopted
     * 
     */
    @XmlEnumValue("adopted")
    ADOPTED("adopted"),

    /**
     * date identifies when resource was deprecated
     * 
     */
    @XmlEnumValue("deprecated")
    DEPRECATED("deprecated"),

    /**
     * date identifies when resource was  superseded or replaced by another resource
     * 
     */
    @XmlEnumValue("superseded")
    SUPERSEDED("superseded"),

    /**
     * time at which the data are considered to become valid.  NOTE: There could be quite a delay between creation and validity begins
     * 
     */
    @XmlEnumValue("validityBegins")
    VALIDITY_BEGINS("validityBegins"),

    /**
     * time at which the data are no longer considered to be valid
     * 
     */
    @XmlEnumValue("validityExpires")
    VALIDITY_EXPIRES("validityExpires"),

    /**
     * the date that the resource shall be released for public access
     * 
     */
    @XmlEnumValue("released")
    RELEASED("released"),

    /**
     * date identifies when an instance of the resource was distributed
     * 
     */
    @XmlEnumValue("distribution")
    DISTRIBUTION("distribution");
    private final String value;

    DateTypeCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DateTypeCode fromValue(String v) {
        for (DateTypeCode c: DateTypeCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
