//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.18 at 02:24:22 PM BST 
//


package _int.iho.s100ci;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * The rolecode property is for use when roles must be allowed to be nilled.
 * 
 * <p>Java class for S100_RoleCode_PropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S100_RoleCode_PropertyType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.iho.int/S100CI&gt;RoleCode"&gt;
 *       &lt;attribute ref="{http://www.iho.int/S100CI}nilReason"/&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S100_RoleCode_PropertyType", propOrder = {
    "value"
})
public class S100RoleCodePropertyType {

    @XmlValue
    protected RoleCode value;
    @XmlAttribute(name = "nilReason", namespace = "http://www.iho.int/S100CI")
    protected List<String> nilReasons;

    /**
     * V. 4.0.0: added author, sponsor, coAuthor, collaborator, editor, mediator, rightsHolder, contributor, funder, stakeholder (19115-1); added definitions
     * 
     * @return
     *     possible object is
     *     {@link RoleCode }
     *     
     */
    public RoleCode getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleCode }
     *     
     */
    public void setValue(RoleCode value) {
        this.value = value;
    }

    /**
     * Gets the value of the nilReasons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nilReasons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNilReasons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNilReasons() {
        if (nilReasons == null) {
            nilReasons = new ArrayList<String>();
        }
        return this.nilReasons;
    }

}
