//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.18 at 04:32:24 PM BST 
//


package org.efficiensea2.maritime_cloud.service_registry.v1.servicespecificationschema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Describes the vendor producing and/or providing the service instance.
 *                 Contains the same information as the AuthorInfo plus the isCommercial flag.
 * 
 *                 - isCommercial Optional indication on the commercial status of the vendor.
 *             
 * 
 * <p>Java class for VendorInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VendorInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://efficiensea2.org/maritime-cloud/service-registry/v1/ServiceSpecificationSchema.xsd}AuthorInfo"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isCommercial" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VendorInfo", propOrder = {
    "isCommercial"
})
public class VendorInfo
    extends AuthorInfo
{

    protected Boolean isCommercial;

    /**
     * Gets the value of the isCommercial property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCommercial() {
        return isCommercial;
    }

    /**
     * Sets the value of the isCommercial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCommercial(Boolean value) {
        this.isCommercial = value;
    }

}
